[package]
name = "spartan_test"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spartan = "0.3.0"
merlin = "3.0.0"
curve25519-dalek = "3.1.0"
rand = "0.8.3"
ndarray-npy = "0.8.0"
ndarray = "0.15.2"
